from apps.accounts.serializers.auth import LoginSerializer, RelativeSignUpSerializer, CaregiverSignUpSerializer
from apps.accounts.serializers.patient import PatientCreateSerializer, PatientUpdateSerializer, PatientResponseSerializer
from apps.accounts.serializers.relative import AddRelativeSerializer
from apps.accounts.serializers.caregiver import CaregiverOfferSerializer, ContractActionSerializer, MedicationEntrySerializer, MedicationScheduleSerializer
from apps.accounts.serializers.admin import SetSalarySerializer
from apps.accounts.serializers.common import UserResponseSerializer, AlertUpdateSerializer
